### ISSUE TITLE
Error while running the inference.py script

### ISSUE THREAD

**Issue by czuczorf** [cnnlstm/DiffusionMat#5]
Hello,
Amazing work, this looks promising!

I've set it up on Windows WSL 2.0 - Ubuntu, using Anaconda. I've finally got to the point where CUDA is available.
By running the inference.py script I got the following error:

CUDA_LAUNCH_BLOCKING=1 python inference.py --exp samples/alphas_pred  --config matte.yml --delta_config deltablock.yml --sample -i images --t 250 --sample_step 5 --ni

INFO - inference.py - 2023-12-08 15:26:05,616 - Using device: cuda
Namespace(data=Namespace(channels=1, dataset='Matting', gaussian_dequantization=False, image_size=256, logit_transform=False, num_workers=32, random_flip=True, rescaled=True, uniform_dequantization=False), device=device(type='cuda'), diffusion=Namespace(beta_end=0.02, beta_schedule='linear', beta_start=0.0001, num_diffusion_timesteps=1000), model=Namespace(ch=128, ch_mult=[1, 1, 2, 2, 4, 4], dropout=0.0, ema=True, ema_rate=0.999, in_channels=1, num_res_blocks=2, out_ch=1, resamp_with_conv=True, type='simple', var_type='fixedsmall'), optim=Namespace(amsgrad=False, beta1=0.9, eps=1e-08, lr=0.0001, optimizer='Adam', weight_decay=0.0), sampling=Namespace(batch_size=30, last_only=True), training=Namespace(batch_size=9, n_epochs=15000, n_iters=5000000, snapshot_freq=5000, validation_freq=2000))
Namespace(data=Namespace(category='PortMatting', channels=1, dataset='PortMatting', gaussian_dequantization=False, image_size=256, logit_transform=False, num_workers=0, random_flip=True, rescaled=True, uniform_dequantization=False), diffusion=Namespace(beta_end=0.02, beta_schedule='linear', beta_start=0.0001, num_diffusion_timesteps=500), model=Namespace(ch=64, ch_mult=[1, 1, 2, 2, 4, 4], dropout=0.0, ema=True, ema_rate=0.999, in_channels=4, num_res_blocks=2, out_ch=1, resamp_with_conv=True, type='simple', var_type='fixedsmall'), optim=Namespace(amsgrad=False, beta1=0.5, eps=1e-08, lr=0.0001, optimizer='Adam', weight_decay=0.0), training=Namespace(batch_size=8, last_only=True))
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
INFO - inference.py - 2023-12-08 15:26:05,617 - Exp instance id = 837
INFO - inference.py - 2023-12-08 15:26:05,617 - Exp comment =
INFO - inference.py - 2023-12-08 15:26:05,617 - Config =
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SwinTransformerSys expand initial----depths:[2, 2, 6, 2];depths_decoder:[1, 2, 2, 2];drop_path_rate:0.1;num_classes:32
---final upsample expand_first---
/home/czuczr/DiffusionMat/runners/diffusion_utils.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  out = torch.gather(torch.tensor(a, dtype=torch.float, device=t.device), 0, t.long())
libpng warning: iCCP: known incorrect sRGB profile
ERROR - inference.py - 2023-12-08 15:26:31,356 - Traceback (most recent call last):
  File "inference.py", line 109, in main
    runner.image_matting_train()
  File "/home/czuczr/DiffusionMat/runners/diffusionmat_test.py", line 244, in image_matting_train
    x_inv,_ = ddim_denoising_step(x_inv, t=t, t_next=t_prev, model=matting_model,
  File "/home/czuczr/DiffusionMat/runners/diffusion_utils.py", line 33, in ddim_denoising_step
    et = model(xt, t)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/czuczr/DiffusionMat/model.py", line 235, in forward
    h = layer(h, temb)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/czuczr/DiffusionMat/model.py", line 152, in forward
    h = self.block1(x)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/czuczr/anaconda3/envs/snowflakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/czuczr/DiffusionMat/model.py", line 10, in forward
    return x * torch.sigmoid(x)
RuntimeError: CUDA error: unknown error

Do you have any idea what this is related to?
Thanks in advance!

**Comment by cnnlstm** [comment]
Thanks for your interest, but I did not meet that error, I hope this [link](https://github.com/pytorch/pytorch/issues/49081) can help you.
